name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'weather-api-test'
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  PROJECT_PATH: './WebApplication1/WebApplication1.csproj'
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      # Build entry project
      - name: Build Entry Project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      # Publish entry project
      - name: Publish Entry Project
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./publish    
      
      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
